add1=["President Clinton, distinguished guests and my fellow citizens, the peaceful transfer of authority is rare in history, yet common in our country. With a simple oath, we affirm old traditions and make new beginnings",
"As I begin, I thank President Clinton for his service to our nation.",
"And I thank Vice President Gore for a contest conducted with spirit and ended with grace.",
"I am honored and humbled to stand here, where so many of America's leaders have come before me, and so many will follow.",
"We have a place, all of us, in a long story - a story we continue, but whose end we will not see. It is the story of a new world that became a friend and liberator of the old, a story of a slave-holding society that became a servant of freedom, the story of a power that went into the world to protect but not possess, to defend but not to conquer.",
"It is the American story - a story of flawed and fallible people, united across the generations by grand and enduring ideals.",
"The grandest of these ideals is an unfolding American promise that everyone belongs, that everyone deserves a chance, that no insignificant person was ever born.",
"Americans are called to enact this promise in our lives and in our laws. And though our nation has sometimes halted, and sometimes delayed, we must follow no other course.",
"Through much of the last century, America's faith in freedom and democracy was a rock in a raging sea. Now it is a seed upon the wind, taking root in many nations.",
"Our democratic faith is more than the creed of our country, it is the inborn hope of our humanity, an ideal we carry but do not own, a trust we bear and pass along. And even after nearly 225 years, we have a long way yet to travel.",
"While many of our citizens prosper, others doubt the promise, even the justice, of our own country. The ambitions of some Americans are limited by failing schools and hidden prejudice and the circumstances of their birth. And sometimes our differences run so deep, it seems we share a continent, but not a country.",
"We do not accept this, and we will not allow it. Our unity, our union, is the serious work of leaders and citizens in every generation. And this is my solemn pledge: I will work to build a single nation of justice and opportunity.",
"I know this is in our reach because we are guided by a power larger than ourselves who creates us equal in His image.",
"And we are confident in principles that unite and lead us onward.",
"America has never been united by blood or birth or soil. We are bound by ideals that move us beyond our backgrounds, lift us above our interests and teach us what it means to be citizens. Every child must be taught these principles. Every citizen must uphold them. And every immigrant, by embracing these ideals, makes our country more, not less, American.",
"Today, we affirm a new commitment to live out our nation's promise through civility, courage, compassion and character.",
"America, at its best, matches a commitment to principle with a concern for civility. A civil society demands from each of us good will and respect, fair dealing and forgiveness.",
"Some seem to believe that our politics can afford to be petty because, in a time of peace, the stakes of our debates appear small.",
"But the stakes for America are never small. If our country does not lead the cause of freedom, it will not be led. If we do not turn the hearts of children toward knowledge and character, we will lose their gifts and undermine their idealism. If we permit our economy to drift and decline, the vulnerable will suffer most.",
"We must live up to the calling we share. Civility is not a tactic or a sentiment. It is the determined choice of trust over cynicism, of community over chaos. And this commitment, if we keep it, is a way to shared accomplishment.",
"America, at its best, is also courageous.",
"Our national courage has been clear in times of depression and war, when defending common dangers defined our common good. Now we must choose if the example of our fathers and mothers will inspire us or condemn us. We must show courage in a time of blessing by confronting problems instead of passing them on to future generations.",
"Together, we will reclaim America's schools, before ignorance and apathy claim more young lives.",
"We will reform Social Security and Medicare, sparing our children from struggles we have the power to prevent. And we will reduce taxes, to recover the momentum of our economy and reward the effort and enterprise of working Americans.",
"We will build our defenses beyond challenge, lest weakness invite challenge.",
"We will confront weapons of mass destruction, so that a new century is spared new horrors.",
"The enemies of liberty and our country should make no mistake: America remains engaged in the world by history and by choice, shaping a balance of power that favors freedom. We will defend our allies and our interests. We will show purpose without arrogance. We will meet aggression and bad faith with resolve and strength. And to all nations, we will speak for the values that gave our nation birth.",
"America, at its best, is compassionate. In the quiet of American conscience, we know that deep, persistent poverty is unworthy of our nation's promise.",
"And whatever our views of its cause, we can agree that children at risk are not at fault. Abandonment and abuse are not acts of God, they are failures of love.",
"And the proliferation of prisons, however necessary, is no substitute for hope and order in our souls.",
"Where there is suffering, there is duty. Americans in need are not strangers, they are citizens, not problems, but priorities. And all of us are diminished when any are hopeless.",
"Government has great responsibilities for public safety and public health, for civil rights and common schools. Yet compassion is the work of a nation, not just a government.",
"And some needs and hurts are so deep they will only respond to a mentor's touch or a pastor's prayer. Church and charity, synagogue and mosque lend our communities their humanity, and they will have an honored place in our plans and in our laws.",
"Many in our country do not know the pain of poverty, but we can listen to those who do.",
"And I can pledge our nation to a goal: When we see that wounded traveler on the road to Jericho, we will not pass to the other side.",
"America, at its best, is a place where personal responsibility is valued and expected.",
"Encouraging responsibility is not a search for scapegoats, it is a call to conscience. And though it requires sacrifice, it brings a deeper fulfillment. We find the fullness of life not only in options, but in commitments. And we find that children and community are the commitments that set us free.",
"Our public interest depends on private character, on civic duty and family bonds and basic fairness, on uncounted, unhonored acts of decency which give direction to our freedom.",
"Sometimes in life we are called to do great things. But as a saint of our times has said, every day we are called to do small things with great love. The most important tasks of a democracy are done by everyone.",
"I will live and lead by these principles: to advance my convictions with civility, to pursue the public interest with courage, to speak for greater justice and compassion, to call for responsibility and try to live it as well.",
"In all these ways, I will bring the values of our history to the care of our times.",
"What you do is as important as anything government does. I ask you to seek a common good beyond your comfort; to defend needed reforms against easy attacks; to serve your nation, beginning with your neighbor. I ask you to be citizens: citizens, not spectators; citizens, not subjects; responsible citizens, building communities of service and a nation of character.",
"Americans are generous and strong and decent, not because we believe in ourselves, but because we hold beliefs beyond ourselves. When this spirit of citizenship is missing, no government program can replace it. When this spirit is present, no wrong can stand against it.",
"After the Declaration of Independence was signed, Virginia statesman John Page wrote to Thomas Jefferson: “We know the race is not to the swift nor the battle to the strong. Do you not think an angel rides in the whirlwind and directs this storm?”",
"Much time has passed since Jefferson arrived for his inauguration. The years and changes accumulate. But the themes of this day he would know: our nation's grand story of courage and its simple dream of dignity.",
"We are not this story's author, who fills time and eternity with his purpose. Yet his purpose is achieved in our duty, and our duty is fulfilled in service to one another.",
"Never tiring, never yielding, never finishing, we renew that purpose today, to make our country more just and generous, to affirm the dignity of our lives and every life.",
"This work continues. This story goes on. And an angel still rides in the whirlwind and directs this storm.",
"God bless you all, and God bless America."]
add2=["Vice President Cheney, Mr. Chief Justice, President Carter, President Bush, President Clinton, reverend clergy, distinguished guests, fellow citizens :"
,"On this day, prescribed by law and marked by ceremony, we celebrate the durable wisdom of our Constitution, and recall the deep commitments that unite our country. I am grateful for the honor of this hour, mindful of the consequential times in which we live, and determined to fulfill the oath that I have sworn and you have witnessed."
,"At this second gathering, our duties are defined not by the words I use, but by the history we have seen together. For a half century, America defended our own freedom by standing watch on distant borders. After the shipwreck of communism came years of relative quiet, years of repose, years of sabbatical —and then there came a day of fire."
,"We have seen our vulnerability —and we have seen its deepest source. For as long as whole regions of the world simmer in resentment and tyranny —prone to ideologies that feed hatred and excuse murder — violence will gather, and multiply in destructive power, and cross the most defended borders, and raise a mortal threat. There is only one force of history that can break the reign of hatred and resentment, and expose the pretensions of tyrants, and reward the hopes of the decent and tolerant, and that is the force of human freedom."
,"We are led, by events and common sense, to one conclusion: The survival of liberty in our land increasingly depends on the success of liberty in other lands. The best hope for peace in our world is the expansion of freedom in all the world."
,"America's vital interests and our deepest beliefs are now one. From the day of our Founding, we have proclaimed that every man and woman on this earth has rights, and dignity, and matchless value, because they bear the image of the Maker of Heaven and earth. Across the generations we have proclaimed the imperative of self-government, because no one is fit to be a master, and no one deserves to be a slave. Advancing these ideals is the mission that created our Nation. It is the honorable achievement of our fathers. Now it is the urgent requirement of our nation's security, and the calling of our time."
,"So it is the policy of the United States to seek and support the growth of democratic movements and institutions in every nation and culture, with the ultimate goal of ending tyranny in our world."
,"This is not primarily the task of arms, though we will defend ourselves and our friends by force of arms when necessary. Freedom, by its nature, must be chosen, and defended by citizens, and sustained by the rule of law and the protection of minorities. And when the soul of a nation finally speaks, the institutions that arise may reflect customs and traditions very different from our own. America will not impose our own style of government on the unwilling. Our goal instead is to help others find their own voice, attain their own freedom, and make their own way."
,"The great objective of ending tyranny is the concentrated work of generations. The difficulty of the task is no excuse for avoiding it. America's influence is not unlimited, but fortunately for the oppressed, America's influence is considerable, and we will use it confidently in freedom's cause."
,"My most solemn duty is to protect this nation and its people against further attacks and emerging threats. Some have unwisely chosen to test America's resolve, and have found it firm."
,"We will persistently clarify the choice before every ruler and every nation: The moral choice between oppression, which is always wrong, and freedom, which is eternally right. America will not pretend that jailed dissidents prefer their chains, or that women welcome humiliation and servitude, or that any human being aspires to live at the mercy of bullies."
,"We will encourage reform in other governments by making clear that success in our relations will require the decent treatment of their own people. America's belief in human dignity will guide our policies, yet rights must be more than the grudging concessions of dictators; they are secured by free dissent and the participation of the governed. In the long run, there is no justice without freedom, and there can be no human rights without human liberty."
,"Some, I know, have questioned the global appeal of liberty —though this time in history, four decades defined by the swiftest advance of freedom ever seen, is an odd time for doubt. Americans, of all people, should never be surprised by the power of our ideals. Eventually, the call of freedom comes to every mind and every soul. We do not accept the existence of permanent tyranny because we do not accept the possibility of permanent slavery. Liberty will come to those who love it."
,"Today, America speaks anew to the peoples of the world :"
,"All who live in tyranny and hopelessness can know: the United States will not ignore your oppression, or excuse your oppressors. When you stand for your liberty, we will stand with you."
,"Democratic reformers facing repression, prison, or exile can know: America sees you for who you are: the future leaders of your free country."
,"The rulers of outlaw regimes can know that we still believe as Abraham Lincoln did :","Those who deny freedom to others deserve it not for themselves; and, under the rule of a just God, cannot long retain it."
,"The leaders of governments with long habits of control need to know: To serve your people you must learn to trust them. Start on this journey of progress and justice, and America will walk at your side."
,"And all the allies of the United States can know: we honor your friendship, we rely on your counsel, and we depend on your help. Division among free nations is a primary goal of freedom's enemies. The concerted effort of free nations to promote democracy is a prelude to our enemies' defeat."
,"Today, I also speak anew to my fellow citizens :"
,"From all of you, I have asked patience in the hard task of securing America, which you have granted in good measure. Our country has accepted obligations that are difficult to fulfill, and would be dishonorable to abandon. Yet because we have acted in the great liberating tradition of this nation, tens of millions have achieved their freedom. And as hope kindles hope, millions more will find it. By our efforts, we have lit a fire as well —a fire in the minds of men. It warms those who feel its power, it burns those who fight its progress, and one day this untamed fire of freedom will reach the darkest corners of our world."
,"A few Americans have accepted the hardest duties in this cause —in the quiet work of intelligence and diplomacy ... the idealistic work of helping raise up free governments ... the dangerous and necessary work of fighting our enemies. Some have shown their devotion to our country in deaths that honored their whole lives —and we will always honor their names and their sacrifice."
,"All Americans have witnessed this idealism, and some for the first time. I ask our youngest citizens to believe the evidence of your eyes. You have seen duty and allegiance in the determined faces of our soldiers. You have seen that life is fragile, and evil is real, and courage triumphs. Make the choice to serve in a cause larger than your wants, larger than yourself —and in your days you will add not just to the wealth of our country, but to its character."
,"America has need of idealism and courage, because we have essential work at home —the unfinished work of American freedom. In a world moving toward liberty, we are determined to show the meaning and promise of liberty."
,"In America's ideal of freedom, citizens find the dignity and security of economic independence, instead of laboring on the edge of subsistence. This is the broader definition of liberty that motivated the Homestead Act, the Social Security Act, and the G.I. Bill of Rights. And now we will extend this vision by reforming great institutions to serve the needs of our time. To give every American a stake in the promise and future of our country, we will bring the highest standards to our schools, and build an ownership society. We will widen the ownership of homes and businesses, retirement savings and health insurance —preparing our people for the challenges of life in a free society. By making every citizen an agent of his or her own destiny, we will give our fellow Americans greater freedom from want and fear, and make our society more prosperous and just and equal."
,"In America's ideal of freedom, the public interest depends on private character —on integrity, and tolerance toward others, and the rule of conscience in our own lives. Self-government relies, in the end, on the governing of the self. That edifice of character is built in families, supported by communities with standards, and sustained in our national life by the truths of Sinai, the Sermon on the Mount, the words of the Koran, and the varied faiths of our people. Americans move forward in every generation by reaffirming all that is good and true that came before —ideals of justice and conduct that are the same yesterday, today, and forever."
,"In America's ideal of freedom, the exercise of rights is ennobled by service, and mercy, and a heart for the weak. Liberty for all does not mean independence from one another. Our nation relies on men and women who look after a neighbor and surround the lost with love. Americans, at our best, value the life we see in one another, and must always remember that even the unwanted have worth. And our country must abandon all the habits of racism, because we cannot carry the message of freedom and the baggage of bigotry at the same time."
,"From the perspective of a single day, including this day of dedication, the issues and questions before our country are many. From the viewpoint of centuries, the questions that come to us are narrowed and few. Did our generation advance the cause of freedom? And did our character bring credit to that cause?"
,"These questions that judge us also unite us, because Americans of every party and background, Americans by choice and by birth, are bound to one another in the cause of freedom. We have known divisions, which must be healed to move forward in great purposes —and I will strive in good faith to heal them. Yet those divisions do not define America. We felt the unity and fellowship of our nation when freedom came under attack, and our response came like a single hand over a single heart. And we can feel that same unity and pride whenever America acts for good, and the victims of disaster are given hope, and the unjust encounter justice, and the captives are set free."
,"We go forward with complete confidence in the eventual triumph of freedom. Not because history runs on the wheels of inevitability; it is human choices that move events. Not because we consider ourselves a chosen nation; God moves and chooses as He wills. We have confidence because freedom is the permanent hope of mankind, the hunger in dark places, the longing of the soul. When our Founders declared a new order of the ages; when soldiers died in wave upon wave for a union based on liberty; when citizens marched in peaceful outrage under the banner ","Freedom Now"," —they were acting on an ancient hope that is meant to be fulfilled. History has an ebb and flow of justice, but history also has a visible direction, set by liberty and the Author of Liberty."
,"When the Declaration of Independence was first read in public and the Liberty Bell was sounded in celebration, a witness said, ","It rang as if it meant something."," In our time it means something still. America, in this young century, proclaims liberty throughout all the world, and to all the inhabitants thereof. Renewed in our strength — tested, but not weary — we are ready for the greatest achievements in the history of freedom."
,"May God bless you, and may He watch over the United States of America."]
word1=dict()
word2=dict()
num1=[0,0,0,0,0,0,0,0,0,0]
wordlist1=["","","","","","","","","",""]
num2=[0,0,0,0,0,0,0,0,0,0]
wordlist2=["","","","","","","","","",""]
def countwords(add1,num1,word1,wordlist1):
    for i in add1:
        words=i.lower()
        words=words.split()
        for l in words:
            if l not in word1:
                word1[l]=1
            else:
                word1[l]=word1[l]+1
    for i in word1:
        for number in range(0,10):
            if word1[i]>num1[number]:
                num1[number]=word1[i]
                wordlist1[number]=i
                break
    print num1
    print wordlist1
countwords(add1,num1,word1,wordlist1)
countwords(add2,num2,word2,wordlist2)